/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stdio.h>
 #include "usart.h"






int main(void)
{
	uart2_tx_init();
	while (1)
	{
		printf("Hello world \n \r");
		__io__putchar('a');
		for(int i=0;i<1000000;i++){}
		__io__putchar('\n');
	}
}


