/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f767xx.h"
#include <stdint.h>


#define GPIOA_EN         (1U<<0)
#define USART_EN         (1U<<17)
#define SYS_FREQ         16000000
#define APB1_CLK         SYS_FREQ
#define UART_BAUDRATE    115200

#define CR1_TE			 (1U<<3)
#define USART_UE     (1U<<0)

static void uart_set_baudrate(USART_TypeDef *USARTx,uint32_t Periphclk, uint32_t Baudrate);
static uint16_t compute_uart_bd(uint32_t Periphclk, uint32_t Baudrate);
void uart2_tx_init(void);

int main(void)
{
	while (1)
	{

	}
}

void uart2_tx_init(void)
{

	/*	Configure the UART GPIO pins */
	//	1. Enable clock access to GPIOA
	RCC->AHB1ENR |= GPIOA_EN;
	//	2. Set PA2 mode as alternate function
	GPIOA->MODER  &=~(1U<<4);
	GPIOA->MODER  |= (1U<<5);
	//	3. Set PA2 alternate function type to UART_TX(AF7)
	GPIOA->AFR[0] |=(1U<<8);
	GPIOA->AFR[0] |=(1U<<9);
	GPIOA->AFR[0] |=(1U<<10);
	GPIOA->AFR[0] &=~(1U<<11);


	/*	Configure the USART module */
	//	1. Enable clock access to UART2
	RCC->APB1ENR |= USART_EN;
	//	2. Configure the buadrate
	uart_set_baudrate(USART2, APB1_CLK, UART_BAUDRATE);
	//	3. Configure the transfer direction as Tx
	USART2->CR1 = CR1_TE;
	//	4. Enable the UART module.
	USART2->CR1 |= USART_UE;



}

static void uart_set_baudrate(USART_TypeDef *USARTx,uint32_t Periphclk, uint32_t Baudrate)
{

	USARTx->BRR =  compute_uart_bd(Periphclk, Baudrate);
}



static uint16_t compute_uart_bd(uint32_t Periphclk, uint32_t Baudrate)
{
	uint16_t result = (Periphclk + (Baudrate / 2U)/Baudrate);
	return result;
}


